### ISSUE TITLE
Questions about auxiliary loss

### ISSUE THREAD

**Issue by hjx-zju** [Dan8991/SMCEPR_pytorch#2]
Hi, thank you for your great work!
I noticed that the EntropyBottleneck has an auxiliary loss which, according to the CompressAI documentation, is supposed to be optimized during or after training. However, I didn't find this being minimized in your implementation. Should this auxiliary loss be minimized?

**Comment by Dan8991** [comment]
Hi, yes you can minimize it, what it does is that it optimizes the center bins in the factorized prior model. It can improve the performance slightly but it's not critical, feel free to add it.

**Comment by hjx-zju** [comment]
Got it，thanks
